name: ktypr_env2
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - pip:
    - pyhmmer==0.10.11
    - pandas==2.2.3
    - pyrodigal==3.4.1
    - clinker==0.0.31
    - .